INSERT INTO ACCOUNT ( BALANCE,CREATEDBY,CREATEDDATE,STATUS) VALUES (1000, 'admin',now(), true);
INSERT INTO ACCOUNT ( BALANCE,CREATEDBY,CREATEDDATE,STATUS) VALUES (2000, 'admin',now(), true);
INSERT INTO ACCOUNT ( BALANCE,CREATEDBY,CREATEDDATE,STATUS) VALUES (3000, 'admin',now(), true);
INSERT INTO ACCOUNT ( BALANCE,CREATEDBY,CREATEDDATE,STATUS) VALUES (4000, 'admin',now(), true);
INSERT INTO ACCOUNT ( BALANCE,CREATEDBY,CREATEDDATE,STATUS) VALUES (5000, 'admin',now(), true);

INSERT INTO TRANSACTIONTYPE (NAME,DESCRIPTION,CREATEDBY,CREATEDDATE,STATUS) VALUES ('PAGO','cargo y abono de cuentas', 'admin',now(), true);

INSERT INTO TRANSACTION ( AMOUNT, SENDERACCOUNT, RECEIVERACCOUNT, TRATYPID,CREATEDBY, TRANSACTIONDATE,STATUS) VALUES (700, 5, 4, 1, 'admin',now(), true);

INSERT INTO ACCOUNTTRANSACTION ( TRANSACTIONID, ACCOUNTID, CREATEDBY, CREATEDDATE, STATUS) VALUES (1, 5, 'admin',now(), true);
INSERT INTO ACCOUNTTRANSACTION ( TRANSACTIONID, ACCOUNTID, CREATEDBY, CREATEDDATE, STATUS) VALUES (1, 4, 'admin',now(), true);

UPDATE ACCOUNT SET BALANCE=(BALANCE-700) WHERE ACCOUNTID=5;

UPDATE ACCOUNT SET BALANCE=(BALANCE+700) WHERE ACCOUNTID=4;