--CREAR ESQUEMA DE BASE DE DATOS DESARROLLO SISTEMA PAY ACCONTS APP
CREATE DATABASE db_dtecpayacc;

--CREATE USER 
create user 'utecpayacc'@'%' identified by 'utecpayacc';

--GRANT USAGE ON *.* TO utecpayacc@'%';

GRANT ALL PRIVILEGES ON db_dtecpayacc.* to db_dtecpayacc@'%';

FLUSH PRIVILEGES;

USE db_dtecpayacc;

ALTER USER 'utecpayacc'@'%' IDENTIFIED WITH mysql_native_password BY 'utecpayacc';

DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT(
ACCOUNTID INT NOT NULL AUTO_INCREMENT,
--ACCNUMBER INT UNIQUE NOT NULL,
BALANCE DOUBLE NOT NULL,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT ACCPK PRIMARY KEY (ACCOUNTID) 
);

DROP TABLE IF EXISTS TRANSACTIONTYPE;

CREATE TABLE TRANSACTIONTYPE(
TRATYPID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(256) NOT NULL,
DESCRIPTION VARCHAR(256) NOT NULL,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT TRATYPPK PRIMARY KEY (TRATYPID) 
);

DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE TRANSACTION(
TRANSACTIONID INT NOT NULL AUTO_INCREMENT,
AMOUNT DOUBLE NOT NULL,
SENDERACCOUNT INT NOT NULL,
RECEIVERACCOUNT INT NOT NULL,
TRANSACTIONDATE DATETIME NOT NULL,
TRATYPID INT NOT NULL,
CREATEDBY VARCHAR(256) NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT TRAPK PRIMARY KEY (TRANSACTIONID) 
);

ALTER TABLE TRANSACTION ADD CONSTRAINT TRAFKTRATYPPK FOREIGN KEY (TRATYPID) REFERENCES TRANSACTIONTYPE(TRATYPID);

DROP TABLE IF EXISTS ACCOUNTTRANSACTION;

CREATE TABLE ACCOUNTTRANSACTION(
ACCTRANID INT NOT NULL AUTO_INCREMENT,
TRANSACTIONID INT NOT NULL,
ACCOUNTID INT NOT NULL,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT ACCTRANPK PRIMARY KEY (ACCTRANID) 
);

ALTER TABLE ACCOUNTTRANSACTION ADD CONSTRAINT ATFKACCPK FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID);
ALTER TABLE ACCOUNTTRANSACTION ADD CONSTRAINT ATFKTRAPK FOREIGN KEY (TRANSACTIONID) REFERENCES TRANSACTION(TRANSACTIONID);

DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
USERID INT NOT NULL AUTO_INCREMENT,
FIRSTNAME VARCHAR(256) NOT NULL,
LASTNAME VARCHAR(256) NOT NULL,
ADDRESS VARCHAR(256),
PHONE VARCHAR(10),
PASS VARCHAR(256) NOT NULL,
EMAIL VARCHAR(256) NOT NULL UNIQUE,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT USERPK PRIMARY KEY (USERID) );
